### ISSUE TITLE
App locks with HMR > 3.0, but works with < 3.0

### ISSUE THREAD

**Issue by cmeeren** [elmish/hmr#12]
### Description

I have a problem where if I use version 3 of the HMR nuget, the app locks after the first HMR update after I have made state changes, whereas with version 2, it works fine.

### Repro code

Repro solution: [fulma-demo.zip](https://github.com/elmish/hmr/files/2577503/fulma-demo.zip)

(Not minimal, it's a slightly modified version of https://github.com/MangelMaxime/fulma-demo where I've replaced the app contents with a TodoMVC sample. Contains a lot of dead code from the fulma demo; only the code in `src/App.fs` is relevant.)

1. Run `fake build -t Watch`
2. Open `localhost:8080`
3. Make any Elmish model change (e.g. write in the text field)
4. Make a change in `src/App.fs` that should be visible with HMR (e.g. replace `"TodoMVC"` near the bottom with another string)
5. Observe HMR works
6. Now open `paket.dependencies` and remove `< 3` from `nuget Fable.Elmish.HMR < 3`
7. Run `paket update`
8. Remove `|> Program.withHMR` from `src/App.fs`
9. Repeat 1–5, notice how that the app is locked and won't respond to input.

* elmish version: 2.0.3
* fable-compiler version: 2.0.10 (output of `dotnet fable --version`, don't know if that's the right thing)
* fable-core version: 2.0.1
* Operating system: Win 10

**Comment by cmeeren** [comment]
In fact, it seems to be possible to repro this just using the standard https://github.com/MangelMaxime/fulma-demo without my modifications to the app code.

**Comment by MangelMaxime** [comment]
Ok I think I know the reason.

To detect the HMR in the lazyView we use `if isNull Browser.window?HMR_Count then` but it seems like isn't set...

I don't know why i got it setted in my test app.

**Comment by MangelMaxime** [comment]
Ah ooops....

`HMR_Count` is something coming from my debug app when I was debugging the HMR problems. Will include it in the library nice catch ^^

**Comment by cmeeren** [comment]
> nice catch ^^

Just a lucky break, really. Trying to get the Fulma demo to run on Electron, but I have almost no idea what I'm doing. Pure coincidence that I tracked this down to the version of Fable.Elmish.HMR. Can't even remember now (an hour later) how that happened. Happy to help in any case. :)

**Comment by MangelMaxime** [comment]
But what do you mean by locked ? Because, HMR is indeed not working but the app is still fully functionnal from test.

Did you make a full reload of the tab ?

**Comment by cmeeren** [comment]
In my repro solution you'll easily see what I mean. In the fulma demo, you can try submitting a comment, and observe that nothing happens.

**Comment by MangelMaxime** [comment]
Ok I wasn't testing the submit feature but navigation which was working.

Well, my fix seems to fix your issue finally. Will publish it

**Comment by MangelMaxime** [comment]
Should be fixed in version `3.0.2`.

It has been publish but nuget needs to do it job now.

**Comment by cmeeren** [comment]
Thanks! Will try out.

I see that 3.0.0 was released only a handful of hours ago. I had no idea. Talk about timing!

**Comment by MangelMaxime** [comment]
Ok, I tested the new version in Fulma-demo and it seems to work for me.

Feel free to re-open if needed.

**Comment by cmeeren** [comment]
Works for me too. Thanks a lot!
