### ISSUE TITLE
Fix build.sh permissions for travis

### ISSUE THREAD

**Issue by MangelMaxime** [elmish/hmr#2]
I am under windows and seems like I can't change the permission of `./build.sh` and Travis is failing because of that.

@et1975 If you are under a *nix system can you please fix it for me ?

**Comment by et1975** [comment]
Sure, will do!

**Comment by MangelMaxime** [comment]
Thank you :)

**Comment by et1975** [comment]
BTW, if you have [Linux subsystem](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) you can do this on Windows too! Maybe even with cygwin? Not sure about that one.
`chmod +x build.sh` to the rescue!

**Comment by MangelMaxime** [comment]
I tried to do it. But git didn't detected the change on the permissions.

After, I used `chmod a+x build.sh` should be enough but perhaps not.

**Comment by et1975** [comment]
Hm, maybe you have to be on [VolFs](https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/) for it to work.
