### ISSUE TITLE
TryParse' could not be determined based on type information prior to this program point

### ISSUE THREAD

**Issue by albertwoo** [elmish/hmr#27]
### Description

Because Fable.Elmish.HMR 4.0.1 is using Fable.Elmish.Browser 3.0.1 and that library has bugs when using Fable 3. We need to upgrade the dependencies to improve the user experience otherwise we have to add Fable.Elmish.Browser in our project and use its latest version.

**Comment by MangelMaxime** [comment]
@albertwoo I just released version 4.1.0 which use version 3.0.4 of Fable.Elmish.Browser. Can you please give it a try?
