### ISSUE TITLE
Make Elmish.Hmr support Webpack, Parcel, Vite

### ISSUE THREAD

**Issue by MangelMaxime** [elmish/hmr#29]
Different bundler seems to offer different API with a few minor difference.

See #28 and https://github.com/fable-compiler/fable3-samples/issues/10#issuecomment-875304624

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime I managed to make Elmish.HMR [compatible with both Webpack and Vite/Snowpack](https://github.com/fable-compiler/Fable.Lit/blob/8a024445ca351e9e753401dc1d5d6d775f04afd8/src/Lit.Elmish/Lit.Elmish.HMR.fs#L73-L82) for Fable.Lit. If it's ok with you, I can send a PR to add similar changes here, although my solution is not Lit-specific so it'd be nice to have a common Elmish.HMR that's not dependent on a specific renderer.

I didn't deal with the Navigation issue though. I think we can use `hot.dispose` to remove the old subscriptions, but probably patching all potential Program extensions with subscriptions is not scalable. If termination capabilities were added to Elmish [as discussed here](https://github.com/elmish/elmish/issues/162#issuecomment-962466232), Elmish.HMR could terminate the "old" program and each extension should be responsible of cleaning up after themselves.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro 

I am going to work on this issue (I was waiting to finish Nacara v1 before doing a round of maintenance across my different projects).

I need to refactor the repository structure to make the maintenance easier and also have demo project to tests the different bundler, etc.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Not trying to spam you :)

But as I am not sure if you saw my notification from https://github.com/elmish/hmr/pull/30, I am pinging you here too.

Can you please have a look at my comments from https://github.com/elmish/hmr/pull/30 I have some problem with Vite HMR

**Comment by alfonsogarciacaro** [comment]
Weird, I did miss the notification indeed 😕 Thanks for letting me know! I'll reply in the PR :+1:

**Comment by MangelMaxime** [comment]
Done in #30
