### ISSUE TITLE
When using subscription every version of code is being invoked

### ISSUE THREAD

**Issue by Novakov** [elmish/hmr#4]
### Description

When dispatching message from subscription (e.g. timer) and using HMR application is "looping" through all versions of code.

### Repro code
Repository: https://github.com/Novakov/fable-elmish-hmr-bug
It's `Fable.Template.Elmish.React` stripped down from almost everything to minimal Elmish + React + HMR app.

### Expected and actual results
**Expected**:
After changing code, newest version should be used in browser.

**Actual**:
After changing code, every version of it is used

### Related information 

* fable-elmish version: 1.0
* fable-compiler version: 1.3.1
* fable-core version: 1.3.1
* Operating system: Windows 10 x64, Chrome 63, Node 9.10

**Comment by MangelMaxime** [comment]
I am not sure, I can do something about that.

The problem, is the `setupTimer` is re-created each time the HMR is trigger.
You could avoid this problem by deleting old timer reference.

Something like:

```fs
let setupTimer dispatch =
  let cb () =
    dispatch Do |> ignore

  #if DEBUG
  clearInterval(window?timerID)
  window?timerID <- window.setInterval(cb, 1000)
  #else
  window.setInterval(cb, 1000) |> ignore
  #endif
```

**Comment by Novakov** [comment]
Oh... haven't though of that ;) 

My original problem is not with timers but very very similar (external source of events) and solution should be similar.

Thanks!
